# coding: utf-8

"""
    vCenter Lookup Bridge API

    vCenter Lookup Bridge API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from vcenter_lookup_bridge_client.models.alarm_list_response_schema import AlarmListResponseSchema

from vcenter_lookup_bridge_client.api_client import ApiClient, RequestSerialized
from vcenter_lookup_bridge_client.api_response import ApiResponse
from vcenter_lookup_bridge_client.rest import RESTResponseType


class AlarmsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_alarms(
        self,
        begin_time: Annotated[Optional[StrictStr], Field(description="アラームが発生したと思われる時間帯の開始時間を指定します。(指定しない場合は7日前からのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        end_time: Annotated[Optional[StrictStr], Field(description="アラームが発生したと思われる時間帯の終了時間を指定します。(指定しない場合は現在までのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        days_ago_begin: Annotated[Optional[StrictInt], Field(description="n日前以降に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の開始日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        days_ago_end: Annotated[Optional[StrictInt], Field(description="n日前以前に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の終了日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        hours_ago_begin: Annotated[Optional[StrictInt], Field(description="n時間前以降に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の開始時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        hours_ago_end: Annotated[Optional[StrictInt], Field(description="n時間前以前に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の終了時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        statuses: Annotated[Optional[List[Optional[StrictStr]]], Field(description="アラームのステータスを指定します。")] = None,
        alarm_sources: Annotated[Optional[List[StrictStr]], Field(description="アラームのソースを指定します。")] = None,
        acknowledged: Annotated[Optional[StrictBool], Field(description="アラームが確認済みかどうかを指定します。")] = None,
        offset: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="アラームを取得する際の開始位置を指定します。")] = None,
        max_results: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="アラームを取得する際の最大件数を指定します。")] = None,
        vcenter: Annotated[Optional[StrictStr], Field(description="vCenterの名前を指定します。")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AlarmListResponseSchema:
        """List Alarms

        トリガー済みのアラーム一覧を取得します。

        :param begin_time: アラームが発生したと思われる時間帯の開始時間を指定します。(指定しない場合は7日前からのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type begin_time: str
        :param end_time: アラームが発生したと思われる時間帯の終了時間を指定します。(指定しない場合は現在までのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type end_time: str
        :param days_ago_begin: n日前以降に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の開始日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type days_ago_begin: int
        :param days_ago_end: n日前以前に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の終了日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type days_ago_end: int
        :param hours_ago_begin: n時間前以降に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の開始時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type hours_ago_begin: int
        :param hours_ago_end: n時間前以前に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の終了時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type hours_ago_end: int
        :param statuses: アラームのステータスを指定します。
        :type statuses: List[Optional[str]]
        :param alarm_sources: アラームのソースを指定します。
        :type alarm_sources: List[str]
        :param acknowledged: アラームが確認済みかどうかを指定します。
        :type acknowledged: bool
        :param offset: アラームを取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: アラームを取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_alarms_serialize(
            begin_time=begin_time,
            end_time=end_time,
            days_ago_begin=days_ago_begin,
            days_ago_end=days_ago_end,
            hours_ago_begin=hours_ago_begin,
            hours_ago_end=hours_ago_end,
            statuses=statuses,
            alarm_sources=alarm_sources,
            acknowledged=acknowledged,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AlarmListResponseSchema",
            '404': None,
            '422': "HTTPValidationError",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_alarms_with_http_info(
        self,
        begin_time: Annotated[Optional[StrictStr], Field(description="アラームが発生したと思われる時間帯の開始時間を指定します。(指定しない場合は7日前からのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        end_time: Annotated[Optional[StrictStr], Field(description="アラームが発生したと思われる時間帯の終了時間を指定します。(指定しない場合は現在までのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        days_ago_begin: Annotated[Optional[StrictInt], Field(description="n日前以降に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の開始日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        days_ago_end: Annotated[Optional[StrictInt], Field(description="n日前以前に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の終了日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        hours_ago_begin: Annotated[Optional[StrictInt], Field(description="n時間前以降に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の開始時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        hours_ago_end: Annotated[Optional[StrictInt], Field(description="n時間前以前に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の終了時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        statuses: Annotated[Optional[List[Optional[StrictStr]]], Field(description="アラームのステータスを指定します。")] = None,
        alarm_sources: Annotated[Optional[List[StrictStr]], Field(description="アラームのソースを指定します。")] = None,
        acknowledged: Annotated[Optional[StrictBool], Field(description="アラームが確認済みかどうかを指定します。")] = None,
        offset: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="アラームを取得する際の開始位置を指定します。")] = None,
        max_results: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="アラームを取得する際の最大件数を指定します。")] = None,
        vcenter: Annotated[Optional[StrictStr], Field(description="vCenterの名前を指定します。")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AlarmListResponseSchema]:
        """List Alarms

        トリガー済みのアラーム一覧を取得します。

        :param begin_time: アラームが発生したと思われる時間帯の開始時間を指定します。(指定しない場合は7日前からのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type begin_time: str
        :param end_time: アラームが発生したと思われる時間帯の終了時間を指定します。(指定しない場合は現在までのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type end_time: str
        :param days_ago_begin: n日前以降に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の開始日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type days_ago_begin: int
        :param days_ago_end: n日前以前に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の終了日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type days_ago_end: int
        :param hours_ago_begin: n時間前以降に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の開始時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type hours_ago_begin: int
        :param hours_ago_end: n時間前以前に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の終了時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type hours_ago_end: int
        :param statuses: アラームのステータスを指定します。
        :type statuses: List[Optional[str]]
        :param alarm_sources: アラームのソースを指定します。
        :type alarm_sources: List[str]
        :param acknowledged: アラームが確認済みかどうかを指定します。
        :type acknowledged: bool
        :param offset: アラームを取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: アラームを取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_alarms_serialize(
            begin_time=begin_time,
            end_time=end_time,
            days_ago_begin=days_ago_begin,
            days_ago_end=days_ago_end,
            hours_ago_begin=hours_ago_begin,
            hours_ago_end=hours_ago_end,
            statuses=statuses,
            alarm_sources=alarm_sources,
            acknowledged=acknowledged,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AlarmListResponseSchema",
            '404': None,
            '422': "HTTPValidationError",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_alarms_without_preload_content(
        self,
        begin_time: Annotated[Optional[StrictStr], Field(description="アラームが発生したと思われる時間帯の開始時間を指定します。(指定しない場合は7日前からのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        end_time: Annotated[Optional[StrictStr], Field(description="アラームが発生したと思われる時間帯の終了時間を指定します。(指定しない場合は現在までのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        days_ago_begin: Annotated[Optional[StrictInt], Field(description="n日前以降に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の開始日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        days_ago_end: Annotated[Optional[StrictInt], Field(description="n日前以前に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の終了日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        hours_ago_begin: Annotated[Optional[StrictInt], Field(description="n時間前以降に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の開始時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        hours_ago_end: Annotated[Optional[StrictInt], Field(description="n時間前以前に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の終了時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。")] = None,
        statuses: Annotated[Optional[List[Optional[StrictStr]]], Field(description="アラームのステータスを指定します。")] = None,
        alarm_sources: Annotated[Optional[List[StrictStr]], Field(description="アラームのソースを指定します。")] = None,
        acknowledged: Annotated[Optional[StrictBool], Field(description="アラームが確認済みかどうかを指定します。")] = None,
        offset: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="アラームを取得する際の開始位置を指定します。")] = None,
        max_results: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="アラームを取得する際の最大件数を指定します。")] = None,
        vcenter: Annotated[Optional[StrictStr], Field(description="vCenterの名前を指定します。")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Alarms

        トリガー済みのアラーム一覧を取得します。

        :param begin_time: アラームが発生したと思われる時間帯の開始時間を指定します。(指定しない場合は7日前からのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type begin_time: str
        :param end_time: アラームが発生したと思われる時間帯の終了時間を指定します。(指定しない場合は現在までのアラームを取得します。) \\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type end_time: str
        :param days_ago_begin: n日前以降に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の開始日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type days_ago_begin: int
        :param days_ago_end: n日前以前に発生したアラームを取得します。指定した日数の過去日付で、アラームが発生したと思われる時間帯の終了日を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type days_ago_end: int
        :param hours_ago_begin: n時間前以降に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の開始時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type hours_ago_begin: int
        :param hours_ago_end: n時間前以前に発生したアラームを取得します。指定した時間数の過去で、アラームが発生したと思われる時間帯の終了時間を指定します。\\*\\_time, days_ago\\_\\*, hours_ago\\_\\* パラメータはいずれか1種類のみを指定してください。
        :type hours_ago_end: int
        :param statuses: アラームのステータスを指定します。
        :type statuses: List[Optional[str]]
        :param alarm_sources: アラームのソースを指定します。
        :type alarm_sources: List[str]
        :param acknowledged: アラームが確認済みかどうかを指定します。
        :type acknowledged: bool
        :param offset: アラームを取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: アラームを取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_alarms_serialize(
            begin_time=begin_time,
            end_time=end_time,
            days_ago_begin=days_ago_begin,
            days_ago_end=days_ago_end,
            hours_ago_begin=hours_ago_begin,
            hours_ago_end=hours_ago_end,
            statuses=statuses,
            alarm_sources=alarm_sources,
            acknowledged=acknowledged,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AlarmListResponseSchema",
            '404': None,
            '422': "HTTPValidationError",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_alarms_serialize(
        self,
        begin_time,
        end_time,
        days_ago_begin,
        days_ago_end,
        hours_ago_begin,
        hours_ago_end,
        statuses,
        alarm_sources,
        acknowledged,
        offset,
        max_results,
        vcenter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'statuses': 'multi',
            'alarm_sources': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if begin_time is not None:
            
            _query_params.append(('begin_time', begin_time))
            
        if end_time is not None:
            
            _query_params.append(('end_time', end_time))
            
        if days_ago_begin is not None:
            
            _query_params.append(('days_ago_begin', days_ago_begin))
            
        if days_ago_end is not None:
            
            _query_params.append(('days_ago_end', days_ago_end))
            
        if hours_ago_begin is not None:
            
            _query_params.append(('hours_ago_begin', hours_ago_begin))
            
        if hours_ago_end is not None:
            
            _query_params.append(('hours_ago_end', hours_ago_end))
            
        if statuses is not None:
            
            _query_params.append(('statuses', statuses))
            
        if alarm_sources is not None:
            
            _query_params.append(('alarm_sources', alarm_sources))
            
        if acknowledged is not None:
            
            _query_params.append(('acknowledged', acknowledged))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if max_results is not None:
            
            _query_params.append(('max_results', max_results))
            
        if vcenter is not None:
            
            _query_params.append(('vcenter', vcenter))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/alarms/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


