# coding: utf-8

"""
    vCenter Lookup Bridge API

    vCenter Lookup Bridge API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from vcenter_lookup_bridge_client.models.portgroup_list_response_schema import PortgroupListResponseSchema

from vcenter_lookup_bridge_client.api_client import ApiClient, RequestSerialized
from vcenter_lookup_bridge_client.api_response import ApiResponse
from vcenter_lookup_bridge_client.rest import RESTResponseType


class PortgroupsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_portgroups(
        self,
        tag_category: Annotated[str, Field(min_length=1, strict=True, description="タグのカテゴリを指定します。")],
        tags: Annotated[List[StrictStr], Field(min_length=1, description="タグの名前を指定します。")],
        offset: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="ポートグループ一覧を取得する際の開始位置を指定します。")] = None,
        max_results: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="ポートグループ一覧を取得する際の最大件数を指定します。")] = None,
        vcenter: Annotated[Optional[StrictStr], Field(description="vCenterの名前を指定します。")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PortgroupListResponseSchema:
        """List Portgroups

        タグを指定して、同タグが付与されたポートグループ一覧を取得します。

        :param tag_category: タグのカテゴリを指定します。 (required)
        :type tag_category: str
        :param tags: タグの名前を指定します。 (required)
        :type tags: List[str]
        :param offset: ポートグループ一覧を取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: ポートグループ一覧を取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_portgroups_serialize(
            tag_category=tag_category,
            tags=tags,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PortgroupListResponseSchema",
            '404': None,
            '422': "HTTPValidationError",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_portgroups_with_http_info(
        self,
        tag_category: Annotated[str, Field(min_length=1, strict=True, description="タグのカテゴリを指定します。")],
        tags: Annotated[List[StrictStr], Field(min_length=1, description="タグの名前を指定します。")],
        offset: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="ポートグループ一覧を取得する際の開始位置を指定します。")] = None,
        max_results: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="ポートグループ一覧を取得する際の最大件数を指定します。")] = None,
        vcenter: Annotated[Optional[StrictStr], Field(description="vCenterの名前を指定します。")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PortgroupListResponseSchema]:
        """List Portgroups

        タグを指定して、同タグが付与されたポートグループ一覧を取得します。

        :param tag_category: タグのカテゴリを指定します。 (required)
        :type tag_category: str
        :param tags: タグの名前を指定します。 (required)
        :type tags: List[str]
        :param offset: ポートグループ一覧を取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: ポートグループ一覧を取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_portgroups_serialize(
            tag_category=tag_category,
            tags=tags,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PortgroupListResponseSchema",
            '404': None,
            '422': "HTTPValidationError",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_portgroups_without_preload_content(
        self,
        tag_category: Annotated[str, Field(min_length=1, strict=True, description="タグのカテゴリを指定します。")],
        tags: Annotated[List[StrictStr], Field(min_length=1, description="タグの名前を指定します。")],
        offset: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="ポートグループ一覧を取得する際の開始位置を指定します。")] = None,
        max_results: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="ポートグループ一覧を取得する際の最大件数を指定します。")] = None,
        vcenter: Annotated[Optional[StrictStr], Field(description="vCenterの名前を指定します。")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Portgroups

        タグを指定して、同タグが付与されたポートグループ一覧を取得します。

        :param tag_category: タグのカテゴリを指定します。 (required)
        :type tag_category: str
        :param tags: タグの名前を指定します。 (required)
        :type tags: List[str]
        :param offset: ポートグループ一覧を取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: ポートグループ一覧を取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_portgroups_serialize(
            tag_category=tag_category,
            tags=tags,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PortgroupListResponseSchema",
            '404': None,
            '422': "HTTPValidationError",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_portgroups_serialize(
        self,
        tag_category,
        tags,
        offset,
        max_results,
        vcenter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'tags': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if tag_category is not None:
            
            _query_params.append(('tag_category', tag_category))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if max_results is not None:
            
            _query_params.append(('max_results', max_results))
            
        if vcenter is not None:
            
            _query_params.append(('vcenter', vcenter))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/portgroups/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


