# coding: utf-8

"""
vCenter Lookup Bridge API

vCenter Lookup Bridge API

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from vcenter_lookup_bridge_client.models.vm_list_response_schema import (
    VmListResponseSchema,
)

from vcenter_lookup_bridge_client.api_client import ApiClient, RequestSerialized
from vcenter_lookup_bridge_client.api_response import ApiResponse
from vcenter_lookup_bridge_client.rest import RESTResponseType


class VmsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_vm(
        self,
        vm_instance_uuid: Annotated[
            StrictStr,
            Field(
                description="インスタンスUUIDを指定します。※格納されている仮想マシンフォルダに関係なく、vmFolder属性はnullを返します。"
            ),
        ],
        vcenter: Annotated[StrictStr, Field(description="vCenterの名前を指定します。")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> VmListResponseSchema:
        """Get Vm

        インスタンスUUIDを指定して、単一の仮想マシンの情報を取得します。

        :param vm_instance_uuid: インスタンスUUIDを指定します。※格納されている仮想マシンフォルダに関係なく、vmFolder属性はnullを返します。 (required)
        :type vm_instance_uuid: str
        :param vcenter: vCenterの名前を指定します。 (required)
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_vm_serialize(
            vm_instance_uuid=vm_instance_uuid,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "VmListResponseSchema",
            "404": None,
            "422": "HTTPValidationError",
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_vm_with_http_info(
        self,
        vm_instance_uuid: Annotated[
            StrictStr,
            Field(
                description="インスタンスUUIDを指定します。※格納されている仮想マシンフォルダに関係なく、vmFolder属性はnullを返します。"
            ),
        ],
        vcenter: Annotated[StrictStr, Field(description="vCenterの名前を指定します。")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[VmListResponseSchema]:
        """Get Vm

        インスタンスUUIDを指定して、単一の仮想マシンの情報を取得します。

        :param vm_instance_uuid: インスタンスUUIDを指定します。※格納されている仮想マシンフォルダに関係なく、vmFolder属性はnullを返します。 (required)
        :type vm_instance_uuid: str
        :param vcenter: vCenterの名前を指定します。 (required)
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_vm_serialize(
            vm_instance_uuid=vm_instance_uuid,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "VmListResponseSchema",
            "404": None,
            "422": "HTTPValidationError",
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_vm_without_preload_content(
        self,
        vm_instance_uuid: Annotated[
            StrictStr,
            Field(
                description="インスタンスUUIDを指定します。※格納されている仮想マシンフォルダに関係なく、vmFolder属性はnullを返します。"
            ),
        ],
        vcenter: Annotated[StrictStr, Field(description="vCenterの名前を指定します。")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Vm

        インスタンスUUIDを指定して、単一の仮想マシンの情報を取得します。

        :param vm_instance_uuid: インスタンスUUIDを指定します。※格納されている仮想マシンフォルダに関係なく、vmFolder属性はnullを返します。 (required)
        :type vm_instance_uuid: str
        :param vcenter: vCenterの名前を指定します。 (required)
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_vm_serialize(
            vm_instance_uuid=vm_instance_uuid,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "VmListResponseSchema",
            "404": None,
            "422": "HTTPValidationError",
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _get_vm_serialize(
        self,
        vm_instance_uuid,
        vcenter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if vm_instance_uuid is not None:
            _path_params["vm_instance_uuid"] = vm_instance_uuid
        # process the query parameters
        if vcenter is not None:

            _query_params.append(("vcenter", vcenter))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["basicAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/vms/{vm_instance_uuid}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def list_vms(
        self,
        vm_folders: Annotated[
            List[StrictStr],
            Field(min_length=1, description="仮想マシンフォルダの名前を指定します。"),
        ],
        offset: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=0)]],
            Field(
                description="仮想マシンフォルダ中の仮想マシンを取得する際の開始位置を指定します。"
            ),
        ] = None,
        max_results: Annotated[
            Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]],
            Field(
                description="仮想マシンフォルダ中の仮想マシンを取得する際の最大件数を指定します。"
            ),
        ] = None,
        vcenter: Annotated[
            Optional[StrictStr], Field(description="vCenterの名前を指定します。")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> VmListResponseSchema:
        """List Vms

        仮想マシンフォルダを指定して、同フォルダ中の仮想マシン一覧を取得します。

        :param vm_folders: 仮想マシンフォルダの名前を指定します。 (required)
        :type vm_folders: List[str]
        :param offset: 仮想マシンフォルダ中の仮想マシンを取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: 仮想マシンフォルダ中の仮想マシンを取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_vms_serialize(
            vm_folders=vm_folders,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "VmListResponseSchema",
            "404": None,
            "422": "HTTPValidationError",
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def list_vms_with_http_info(
        self,
        vm_folders: Annotated[
            List[StrictStr],
            Field(min_length=1, description="仮想マシンフォルダの名前を指定します。"),
        ],
        offset: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=0)]],
            Field(
                description="仮想マシンフォルダ中の仮想マシンを取得する際の開始位置を指定します。"
            ),
        ] = None,
        max_results: Annotated[
            Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]],
            Field(
                description="仮想マシンフォルダ中の仮想マシンを取得する際の最大件数を指定します。"
            ),
        ] = None,
        vcenter: Annotated[
            Optional[StrictStr], Field(description="vCenterの名前を指定します。")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[VmListResponseSchema]:
        """List Vms

        仮想マシンフォルダを指定して、同フォルダ中の仮想マシン一覧を取得します。

        :param vm_folders: 仮想マシンフォルダの名前を指定します。 (required)
        :type vm_folders: List[str]
        :param offset: 仮想マシンフォルダ中の仮想マシンを取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: 仮想マシンフォルダ中の仮想マシンを取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_vms_serialize(
            vm_folders=vm_folders,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "VmListResponseSchema",
            "404": None,
            "422": "HTTPValidationError",
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def list_vms_without_preload_content(
        self,
        vm_folders: Annotated[
            List[StrictStr],
            Field(min_length=1, description="仮想マシンフォルダの名前を指定します。"),
        ],
        offset: Annotated[
            Optional[Annotated[int, Field(strict=True, ge=0)]],
            Field(
                description="仮想マシンフォルダ中の仮想マシンを取得する際の開始位置を指定します。"
            ),
        ] = None,
        max_results: Annotated[
            Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]],
            Field(
                description="仮想マシンフォルダ中の仮想マシンを取得する際の最大件数を指定します。"
            ),
        ] = None,
        vcenter: Annotated[
            Optional[StrictStr], Field(description="vCenterの名前を指定します。")
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Vms

        仮想マシンフォルダを指定して、同フォルダ中の仮想マシン一覧を取得します。

        :param vm_folders: 仮想マシンフォルダの名前を指定します。 (required)
        :type vm_folders: List[str]
        :param offset: 仮想マシンフォルダ中の仮想マシンを取得する際の開始位置を指定します。
        :type offset: int
        :param max_results: 仮想マシンフォルダ中の仮想マシンを取得する際の最大件数を指定します。
        :type max_results: int
        :param vcenter: vCenterの名前を指定します。
        :type vcenter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_vms_serialize(
            vm_folders=vm_folders,
            offset=offset,
            max_results=max_results,
            vcenter=vcenter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "VmListResponseSchema",
            "404": None,
            "422": "HTTPValidationError",
            "500": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _list_vms_serialize(
        self,
        vm_folders,
        offset,
        max_results,
        vcenter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            "vm_folders": "multi",
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if vm_folders is not None:

            _query_params.append(("vm_folders", vm_folders))

        if offset is not None:

            _query_params.append(("offset", offset))

        if max_results is not None:

            _query_params.append(("max_results", max_results))

        if vcenter is not None:

            _query_params.append(("vcenter", vcenter))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["basicAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/vms/",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
