# coding: utf-8

"""
    vCenter Lookup Bridge API

    vCenter Lookup Bridge API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AlarmResponseSchema(BaseModel):
    """
    アラームのレスポンススキーマ
    """ # noqa: E501
    acknowledged: StrictBool = Field(description="アラームが確認済みかどうかを示します。")
    acknowledged_time: Optional[StrictStr] = Field(alias="acknowledgedTime")
    alarm_source: Optional[StrictStr] = Field(alias="alarmSource")
    created_time: StrictStr = Field(description="アラームの作成時間を示します。（ISO 8601形式）", alias="createdTime")
    datacenter: Optional[StrictStr]
    description: StrictStr = Field(description="アラームの説明を示します。")
    name: Optional[StrictStr]
    status: StrictStr = Field(description="アラームのステータスを示します。")
    vcenter: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["acknowledged", "acknowledgedTime", "alarmSource", "createdTime", "datacenter", "description", "name", "status", "vcenter"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['red', 'yellow', 'green', 'gray']):
            raise ValueError("must be one of enum values ('red', 'yellow', 'green', 'gray')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlarmResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if acknowledged_time (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_time is None and "acknowledged_time" in self.model_fields_set:
            _dict['acknowledgedTime'] = None

        # set to None if alarm_source (nullable) is None
        # and model_fields_set contains the field
        if self.alarm_source is None and "alarm_source" in self.model_fields_set:
            _dict['alarmSource'] = None

        # set to None if datacenter (nullable) is None
        # and model_fields_set contains the field
        if self.datacenter is None and "datacenter" in self.model_fields_set:
            _dict['datacenter'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if vcenter (nullable) is None
        # and model_fields_set contains the field
        if self.vcenter is None and "vcenter" in self.model_fields_set:
            _dict['vcenter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlarmResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acknowledged": obj.get("acknowledged"),
            "acknowledgedTime": obj.get("acknowledgedTime"),
            "alarmSource": obj.get("alarmSource"),
            "createdTime": obj.get("createdTime"),
            "datacenter": obj.get("datacenter"),
            "description": obj.get("description"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "vcenter": obj.get("vcenter")
        })
        return _obj


