# coding: utf-8

"""
    vCenter Lookup Bridge API

    vCenter Lookup Bridge API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EventResponseSchema(BaseModel):
    """
    イベントのレスポンススキーマ
    """ # noqa: E501
    created_time: StrictStr = Field(description="イベントの作成時間を示します。（ISO 8601形式）", alias="createdTime")
    datacenter: Optional[StrictStr]
    event_source: Optional[StrictStr] = Field(alias="eventSource")
    ip_address: Optional[StrictStr] = Field(alias="ipAddress")
    message: StrictStr = Field(description="イベントのメッセージを示します。")
    user_name: Optional[StrictStr] = Field(alias="userName")
    vcenter: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["createdTime", "datacenter", "eventSource", "ipAddress", "message", "userName", "vcenter"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if datacenter (nullable) is None
        # and model_fields_set contains the field
        if self.datacenter is None and "datacenter" in self.model_fields_set:
            _dict['datacenter'] = None

        # set to None if event_source (nullable) is None
        # and model_fields_set contains the field
        if self.event_source is None and "event_source" in self.model_fields_set:
            _dict['eventSource'] = None

        # set to None if ip_address (nullable) is None
        # and model_fields_set contains the field
        if self.ip_address is None and "ip_address" in self.model_fields_set:
            _dict['ipAddress'] = None

        # set to None if user_name (nullable) is None
        # and model_fields_set contains the field
        if self.user_name is None and "user_name" in self.model_fields_set:
            _dict['userName'] = None

        # set to None if vcenter (nullable) is None
        # and model_fields_set contains the field
        if self.vcenter is None and "vcenter" in self.model_fields_set:
            _dict['vcenter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdTime": obj.get("createdTime"),
            "datacenter": obj.get("datacenter"),
            "eventSource": obj.get("eventSource"),
            "ipAddress": obj.get("ipAddress"),
            "message": obj.get("message"),
            "userName": obj.get("userName"),
            "vcenter": obj.get("vcenter")
        })
        return _obj


