# coding: utf-8

"""
    vCenter Lookup Bridge API

    vCenter Lookup Bridge API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HostResponseSchema(BaseModel):
    """
    ESXiホストのレスポンススキーマ
    """ # noqa: E501
    cluster: Optional[StrictStr]
    cpu_model: StrictStr = Field(description="ESXiホストのCPUモデルを示します。", alias="cpuModel")
    datacenter: StrictStr = Field(description="ESXiホストのデータセンターを示します。")
    datastores: Optional[List[Any]]
    esxi_version: StrictStr = Field(description="ESXiホストのバージョンを示します。", alias="esxiVersion")
    esxi_version_full: StrictStr = Field(description="ESXiホストのビルド番号を含む、バージョンを示します。", alias="esxiVersionFull")
    hardware_model: StrictStr = Field(description="ESXiホストのハードウェアモデルを示します。", alias="hardwareModel")
    hardware_vendor: StrictStr = Field(description="ESXiホストのハードウェアベンダーを示します。", alias="hardwareVendor")
    ip_address: Optional[StrictStr] = Field(alias="ipAddress")
    memory_size_mb: StrictInt = Field(description="ESXiホストのメモリサイズ(MB)を示します。", alias="memorySizeMB")
    name: StrictStr = Field(description="ESXiホストの名前(ホスト名)を示します。")
    num_cpu_cores: StrictInt = Field(description="ESXiホストのCPUコア数を示します。", alias="numCpuCores")
    num_cpu_sockets: StrictInt = Field(description="ESXiホストのCPUソケット数を示します。", alias="numCpuSockets")
    num_cpu_threads: StrictInt = Field(description="ESXiホストのCPUスレッド数を示します。", alias="numCpuThreads")
    portgroups: Optional[List[Any]]
    power_state: StrictStr = Field(description="ESXiホストの電源の状態を示します。", alias="powerState")
    status: StrictStr = Field(description="ESXiホストのステータスを示します。")
    uuid: StrictStr = Field(description="ESXiホストのUUIDを示します。")
    vcenter: Optional[StrictStr]
    vswitches: Optional[List[Any]]
    __properties: ClassVar[List[str]] = ["cluster", "cpuModel", "datacenter", "datastores", "esxiVersion", "esxiVersionFull", "hardwareModel", "hardwareVendor", "ipAddress", "memorySizeMB", "name", "numCpuCores", "numCpuSockets", "numCpuThreads", "portgroups", "powerState", "status", "uuid", "vcenter", "vswitches"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['green', 'yellow', 'red', 'gray']):
            raise ValueError("must be one of enum values ('green', 'yellow', 'red', 'gray')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HostResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cluster (nullable) is None
        # and model_fields_set contains the field
        if self.cluster is None and "cluster" in self.model_fields_set:
            _dict['cluster'] = None

        # set to None if datastores (nullable) is None
        # and model_fields_set contains the field
        if self.datastores is None and "datastores" in self.model_fields_set:
            _dict['datastores'] = None

        # set to None if ip_address (nullable) is None
        # and model_fields_set contains the field
        if self.ip_address is None and "ip_address" in self.model_fields_set:
            _dict['ipAddress'] = None

        # set to None if portgroups (nullable) is None
        # and model_fields_set contains the field
        if self.portgroups is None and "portgroups" in self.model_fields_set:
            _dict['portgroups'] = None

        # set to None if vcenter (nullable) is None
        # and model_fields_set contains the field
        if self.vcenter is None and "vcenter" in self.model_fields_set:
            _dict['vcenter'] = None

        # set to None if vswitches (nullable) is None
        # and model_fields_set contains the field
        if self.vswitches is None and "vswitches" in self.model_fields_set:
            _dict['vswitches'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HostResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cluster": obj.get("cluster"),
            "cpuModel": obj.get("cpuModel"),
            "datacenter": obj.get("datacenter"),
            "datastores": obj.get("datastores"),
            "esxiVersion": obj.get("esxiVersion"),
            "esxiVersionFull": obj.get("esxiVersionFull"),
            "hardwareModel": obj.get("hardwareModel"),
            "hardwareVendor": obj.get("hardwareVendor"),
            "ipAddress": obj.get("ipAddress"),
            "memorySizeMB": obj.get("memorySizeMB"),
            "name": obj.get("name"),
            "numCpuCores": obj.get("numCpuCores"),
            "numCpuSockets": obj.get("numCpuSockets"),
            "numCpuThreads": obj.get("numCpuThreads"),
            "portgroups": obj.get("portgroups"),
            "powerState": obj.get("powerState"),
            "status": obj.get("status"),
            "uuid": obj.get("uuid"),
            "vcenter": obj.get("vcenter"),
            "vswitches": obj.get("vswitches")
        })
        return _obj


